elysiajs/documentation

docs/plugins/cors.md
there is incorrect path and I just correct it
=> change import path

docs/collections/cheat-sheet.md
there is a missing character to import in **Guard** section
=> add a missing character

docs/plugins/swagger.md
there is wrong code in this swagger docs, when I tried it, it's wrong and needs changes maybe normal developers don't can fix it
it'll make the docs clearer
=> Fix some swagger docs's code

docs/collections/plugins.md
=> docs: add rate limit plugin

components/landing/familiar.vue, components/landing/get-start.vue, components/landing/heading.vue
=> point to a valid cheat-sheet page

docs/patterns/websocket.md
This is documentation for https://github.com/elysiajs/elysia/pull/33 and can be merged after that.
=> Add support for "parse" hook.

docs/plugins/overview.md
=> docs: add logger plugin

docs/plugins/cron.md
This documentation section should be removed.
=> remove wrong documentation

docs/plugins/overview.md
Added decorators plugin to community plugins list
=> Add decorators plugin

docs/plugins/overview.md
Adds [elysia-basic-auth](https://github.com/itsyoboieltr/elysia-basic-auth) to community plugins.
=> feat: add elysia-basic-auth on community plugins list

docs/plugins/overview.md
Adds [elysia-helmet](https://github.com/DevTobias/elysia-helmet) to community plugins.
=> feat: add elysia-helmet on community plugin list

components/midori/simple.vue
Fixed typo in the landing page
=> fix: little typo

docs/concept/schema.md, docs/patterns/reference-models.md
Also adds typebuilder imports to reference models section
=> Removes unused code and file reference on schema code example

docs/quick-start.md
Update documentation to match the output of running `bun create elysia hi-elysia`
Currently, copy pasting the code from the documentation causes a `'app.server' is possibly 'null'` error, which is confusing for new users like myself
=> Update quick-start.md to fix sample code errors

docs/plugins/eden/overview.md
Just some small edits to help the flow while reading
=> A little English cleanup for Eden's overview.md

docs/plugins/overview.md
Added my [Logysia](https://github.com/tristanisham/logysia) middleware community plugin.
=> added logysia

docs/blog/with-prisma.md
=> fix: Prisma typo

docs/plugins/html.md
This PR introduce all documentation changes needed by https://github.com/elysiajs/elysia-html/pull/13.
I do not have a fluent English, so I'd love if someone could review what I wrote XD
=> Updated documentation for @elysiajs/html.

docs/patterns/remapping.md
I believe this paragraph is form the "Cookie" page and not from this one.
=> Remove description from different page

docs/concept/route.md
Fixing Typos and Grammatical errors in route.md
=> TYPO: fixed typo in route.md

docs/concept/guard.md
update "groupped" to "grouped"
=> fix: typo in Update guard.md

docs/patterns/mount.md
Minor adjustments which make the mount.md docs page more concise and readable.
=> docs: correct grammar, spelling

docs/blog/elysia-07.md
=> fix(elysia-07.md): typo

docs/patterns/websocket.md
Removes references to the WebSocket plugin since it is no longer a plugin.
=> Fix WebSocket plugin references

components/midori/community.vue, components/midori/e2e-type-safety.vue, components/midori/editor.vue, components/midori/fast.vue, components/midori/hero.vue, components/midori/just-return.vue, components/midori/openapi.vue, components/midori/plugins.vue, components/midori/quickstart.vue, components/midori/simple.vue, components/midori/type-strict.vue, components/tailwind.css
Reverts elysiajs/documentation#111
The current one is a little bit too dark, will fine tune later
=> Revert "slightly better contrast ratio of text in light mode for landing page"

docs/plugins/overview.md
Add two plugins I made:
- [Elysia HMR HTML](https://github.com/gtrabanco/elysia-hmr-html) - Reload html files when change any file in a directory
- [Elysia Inject HTML](https://github.com/gtrabanco/elysia-inject-html) - So simple plugin to inject HTML code in HTML files
Elysia HMR HTML is done with Server Sent Events so require a compatible browser with Eventsource.
=> Add community plugins

docs/quick-start.md
Creation of project in Elysia currently listens at 3000 and boilerplate is a little different than currently represented in Docs
=> Update Default Code in index.ts

docs/plugins/overview.md
- Fixed grammar, spelling, and formatting in overview documentation page
=> Enhance overview page documentation

docs/plugins/overview.md
Hello friends of the Elysia community, I am grateful for the contributions of this community. I really enjoy Elysia. I have developed a plugin [elysiajs-nuxt](https://github.com/trylovetom/elysiajs-nuxt) that easily integrates Nuxt with Elysia, and I would like to share this plugin with the community. Based on 
@SaltyAom's [suggestion](https://github.com/elysiajs/elysia/issues/301), it can be added to the plugins awesome list.
If you have any suggestions or questions, feel free to raise them for discussion! I'm looking forward to growing with the community and continuously improving this innovative solution.
=> Add the elysiajs-nuxt plugins

docs/essential/context.md
Fix example code for remap state
=> doc: typo missing closing bracket for example remap state

docs/.vitepress/config.ts, docs/integrations/sveltekit.md
Hi, I really wanted to try running Bun + SvelteKit + Elysia and it appears to be working fine so far. Here comes a guide how to integrate with SvelteKit.
=> Feat/Add SvelteKit integration guide

docs/essential/route.md
=> Fix: Typo fixes in route.md

docs/essential/path.md
Hi!
While reading the docs I found some grammatically incorrect sentences and words and fixed them.
=> Fix: Improved grammar in path.md

docs/introduction.md
This PR fixes a couple of typos and a minor grammatical improvement.
=> Fix: typos and a minor grammatical change

docs/essential/route.md
There was a missing import on Elysia.all section
=> fix: essential/route missing import Elysia.all

docs/concept/schema.md
There was a missing import in a example
=> Fix import

docs/concept/schema.md
=> Fix: broken link

docs/validation/schema-type.md
Corrected the `cookie` & `200` status code table in the elysisa docs [example](https://elysiajs.com/validation/schema-type.html#example-5)
=> cookie & response schema-type correction

docs/patterns/group.md
Changed
| Path     | Result  |
| -------- | ------- |
| /sign-in | Sign in |
| /sign-in | Sign up |
| /sign-in | Profile |
To
| Path     | Result  |
| -------- | ------- |
| /user/sign-in | Sign in |
| /user/sign-in | Sign up |
| /user/sign-in | Profile |
=> Updated `/path` to `/prefix/path` for better clearity in group.md

docs/plugins/jwt.md
From [Discord](https://discord.com/channels/1044804142461362206/1199475043332268053/1199479013534617722)
=> 🔧 fix: jwt plugin example

docs/introduction.md
=> fix discord link

docs/validation/schema-type.md
- Small clarification in the use of content types in `body` for validation. 
- Updates code example to work "out-of-the-box"
https://github.com/elysiajs/elysia/issues/400
=> Issue-400 - clarification of content-type header in relation to body

docs/plugins/html.md
As I was reading the docs I noticed a small markdown issue in the html plugin docs.
Great project! Excited to learn more and more about it
=> docs(html): fix markdown formatting

docs/life-cycle/after-handle.md
Closes https://github.com/elysiajs/documentation/issues/262
=> fix: after handle example

.github/ISSUE_TEMPLATE/1-docs-issue.yml, .github/ISSUE_TEMPLATE/config.yml
Added Github issue templates based on https://github.com/elysiajs/elysia/pull/419 to help us with issues 💫
=> chore: added github issue templates

docs/life-cycle/on-response.md
There was a typo for the response handle that uses before instead. I fixed that.
=> Fixed a little typo for the response handle

docs/essential/context.md, docs/essential/schema.md, docs/essential/scope.md
This will also fix the typo mentioned on #274
=> fix: typos on essential

docs/plugins/overview.md
A highly customisable logging library written for ElysiaJS. Currently unstable, should be production-ready in a week.
=> feat: add Logestic plugin

docs/integrations/drizzle.md
Fixes incorrect expected usage of t.Omit and the createInsertSchema
=> fix: Drizzle docs

docs/essential/route.md
made all demos consistent with code snippets
=> feat: fix `route.md` example demos

docs/plugins/overview.md
I put my plugin first on the list, but you can put it in any position you want, of course.
=> add bunsai to community plugins

docs/plugins/overview.md
ref: https://github.com/macropygia/elysia-openid-client
=> Add elysia-openid-client plugin

docs/plugins/overview.md
[elysia-oauth2](https://github.com/kravetsone/elysia-oauth2) - Elysia plugin for OAuth 2.0 Authorization Flow with more than 42 providers
=> Add elysia-oauth2 plugin

docs/plugins/overview.md
```bash
docs(plugins): add logixlysia to community plugins
```
=> Added Logixlysia to community plugins

docs/life-cycle/trace.md
Thanks for maintaining this awesome project!
=> chore: typo in trace.md

docs/patterns/mvc.md
I thought it was best to stop lurking on saltyAom's twitter and actually use Elysiajs. Found this type while reading thru the great docs.
=> chore: fixed typo

docs/plugins/overview.md
reported on [discord](https://discord.com/channels/1044804142461362206/1044804143455420539/1241461636150071418)
=> 🔧 fix: BunSai repo url

docs/integrations/cheat-sheet.md
Updated to sample code from https://elysiajs.com/patterns/documentation
=> fix(docs): update cheat sheet documentation example code

docs/integrations/cheat-sheet.md
minor to avoid rendering backticks
=> minor Update cheat-sheet.md

docs/validation/schema-type.md
=> fix: minor update schema-type.md

docs/life-cycle/after-handle.md
Hello! I really enjoy Elysia. However, I’ve noticed that the documentation sometimes contains grammatical errors. Since I am already reading the docs, I’d be happy to submit any changes that could enhance the reading experience.
Changes:
=> A pull request for improving the documentation

docs/plugins/overview.md
=> feat: add plugins @chneau/elysia-compression and @chneau/elysia-logger to the list

docs/plugins/cors.md
update document
exposedHeaders to exposeHeaders for @elysiajs/cors plugin
=> Update cors.md in exposeHeaders section

docs/plugins/overview.md
Adding the compressor to the list of plugins compatible with Elysia, we are developing an opinionated boilerplate/framework around Elysia, and this plugin is an integral part of the application's core.
It is fully compatible and tested with the current version of Elysia.
=> Add @labzzhq/compressor plugin

docs/validation/primitive-type.md
To correct the example, change the word 'body' to 'response.'
=> Update primitive-type.md. Change body to reponse

docs/patterns/websocket.md
Today when I read docs from https://elysiajs.com/patterns/websocket.html#websocket-message-validation. In order to find how to get `query`, I spend a lot of time. So I think here should optimize code example.
=> Optimize websocket message validation example

docs/essential/life-cycle.md
Some of the sentences weren't formulated perfectly. With these changes it reads a bit nicer.
=> Fix grammar in life-cycle.md

docs/plugins/overview.md
Repo: https://github.com/tanishqmanuja/nice-logger
NPM: https://www.npmjs.com/package/@tqman/nice-logger
=> docs: add nice-logger to overview.md

docs/integrations/cheat-sheet.md
Changed “JSON to response” to “response to JSON” for better flow
=> Wording changed

docs/tutorial.md
small typo fix of complex which was mispelled as comlex
=> fix(tutorial.md): typo

docs/integrations/expo.md
"thank to" → "thanks to"
Elysia routing will works properly -> Elysia routing will **work** properly "if not exists" → "if it doesn't exist"
Expo Function are treated as Edge function  -> Expo **functions** are treated as Edge **functions**
=> 📘doc: fix grammar

docs/plugins/overview.md
Added @rasla/logify pluggin in documentation.
=> added logify for elysia js

docs/tutorial.md
Fixed small typos and improved sentence structure for clarity.
=> Fix typos in tutorial.md documentation

docs/.vitepress/config.ts, docs/recipe/better-auth.md
This pull request introduces the following changes to the repository:
1. **Update Navigation**: 
- Adds a new navigation link for "Better Auth" in the sidebar configuration (`docs/.vitepress/config.ts`).
2. **Add Documentation**:
- Creates a comprehensive guide for integrating "Better Auth" with ElysiaJS, including installation steps, database setup, and middleware configuration (`docs/recipe/better-auth.md`).
- **Files Updated**:  
- `docs/.vitepress/config.ts`: 4 additions  
- `docs/recipe/better-auth.md`: 176 additions  
Pull Request made with Pr-Buddy ✨
=> docs: add better-auth recipie

docs/plugins/swagger.md
This PR enhances the Swagger documentation for the ElysiaJS project by improving the security section and refining formatting for better clarity and consistency.
1. **Security Section**:  
- Added a detailed guide and code example for configuring Bearer Authentication (using JWT) in Swagger.
- Provided clear instructions for securing API endpoints.
2. **Formatting Improvements**:  
- Updated code blocks and text for improved alignment and readability.
These updates aim to enhance the documentation's usability and professionalism, helping developers secure their APIs more effectively.
=> doc: fix swagger documentation

docs/plugins/static.md
Adds the indexHTML to the config list with description
=> Update static.md to include a missing config

docs/plugins/swagger.md
This was moved in https://github.com/scalar/scalar/pull/2202
=> Update the link to the scalar config

docs/recipe/better-auth.md
This PR resolves a `TypeError: Se[u] is not a function` error during better-auth schema generation. Updated the authentication configuration to align with [official docs](https://www.better-auth.com/docs/installation#authentication-methods).
Changes
- Fixed misconfiguration causing schema generation failure.
=> fix better-auth config

docs/recipe/drizzle.md
=> fix: remove extra closing parenthesis

docs/patterns/macro.md
Hello,
This is a very small PR to fix or rephrase a few sentences in the documentation. No code changes have been made, just minor tweaks to the text ! 
Thanks for reviewing 🙏🏻
=> fix typos in macro.md

docs/plugins/overview.md
Add elysiajs-sync plugin to community plugins page.
Repo here: https://github.com/johnny-woodtke/elysiajs-sync
Show and tell here: https://github.com/elysiajs/elysia/discussions/1030
=> Add Community Plugin

docs/recipe/drizzle.md
Closes https://github.com/elysiajs/documentation/issues/479
Refer to drizzle-typebox [0.2.0](https://github.com/drizzle-team/drizzle-orm/blob/main/changelogs/drizzle-typebox/0.2.0.md) at this [commit](https://github.com/drizzle-team/drizzle-orm/commit/7525e495276e36e8373a7490d040b2e3a0e414a7#diff-7d90493205bcaeed671f6e52a334f23ca2dab23064cf130ac6698db286de25d6) for changes in type exports
createSchemaFactory function was introduced but I do not have any insight as to how useful it is in this context, please advice.
=> Fix ultility function type for drizzle-typebox ^0.2.0

docs/eden/installation.md
=> docs: state that @types/bun is compulsory for eden

docs/plugins/overview.md
- moved XML plugin to new line
- added elysia-protobuf plugin
=> Updated community plugins

docs/key-concept.md
Fixing several typos and weirdly structured sentences.
=> fix(key concepts) Fix several typos and weirdly structured sentences.

docs/plugins/opentelemetry.md
I updated a dead link, really drove me insane :)
=> Update link in opentelemetry plugin docs

docs/plugins/overview.md
Adding new plugin into a community plugin section for more exposure
=> docs: add elysia-remote-dts as new community plugin

docs/integrations/better-auth.md
Reverts elysiajs/documentation#526
Actually it partially works, so the documentation was right.
=> Revert "Update better-auth.md"

docs/plugins/overview.md
Adds the Cap Checkpoint plugin to the plugins list
=> [plugins] Add Cap Checkpoint

docs/plugins/overview.md
Link to CDN Cache repo: https://github.com/johnny-woodtke/elysiajs-cdn-cache
Link to CDN Cache npm package: https://www.npmjs.com/package/elysiajs-cdn-cache
Link to Elysia GitHub discussion: https://github.com/elysiajs/elysia/discussions/1224
=> Add CDN Cache Community Plugin

docs/essential/plugin.md
complete a sentence in Functional callback part
=> doc: fix an incomplete sentence

docs/plugins/overview.md
Line removed.
-   [BunSai](https://github.com/nikiskaarup/bunsai2) - full-stack agnostic framework for the web, built upon Bun and Elysia
=> removed broken link, couldn't find the repo even.

docs/integrations/drizzle.md
Encounter it while copy-pasting as suggested.
=> fix: remove testing code in drizzle utils

docs/essential/validation.md
=> Change UwU by UnU

docs/integrations/cloudflare-worker.md
- Fix incorrect title of `integrations/cloudflare-worker`.
=> Fix title of `integrations/cloudflare-worker`
