elysiajs/documentation

docs/.vitepress/config.ts
I just fixed some minor issues on the sidebar.
Made some of the subheadings plural to make them consistent such as
> Core Concepts
> Collections
Made the `Getting Start` subheading as `Getting Started`
=> Fixed sidebar typos

components/blog/Landing.vue
the blog card's bg color currently turns `gray-50` even on dark mode which makes it unreadable, changed it to `gray-700` as I think that was the intended behavior (didn't make a pr the traditional way as it was a very small change)
=> 🔧 fix: blog card bg color on focus

docs/concept/plugin.md
Fix example showing custom plugin parameter destructuring.
By using `:` we are renaming variable `prefix` to `/v1` that won't work.. so fixes this
=> 🔧 fix: default param on destructuring example

docs/collections/plugins.md
Fixes link to documentation repository in a plugin section
=> 🔧 fix: link to documentation repository

docs/plugins/swagger.md
Swagger plugin field key should be `documentation` instead of `swagger`:
https://github.com/elysiajs/elysia-swagger/blob/8fa26e6a72e21b2ce6fbec37e9f8c93af791f296/src/index.ts#L19
=> Update swagger.md typo

components/landing/heading.vue
I noticed the "ps. it take < 30 seconds to start" section under the "Get Started" button was missing an "s", thought I'd submit a quick PR to fix it.
Thanks!
=> added missing "s"

docs/patterns/websocket.md
- corrected some minor grammar issues 
- moved the text about configuration from the main heading to the configuration header.
- rephrased some sentences 
---
The links used to link to bun's `readme.md` on their [github page](https://github.com/oven-sh/bun#websockets-with-bunserve) but recently they've created a website for their documentation. I am not sure what it should link to; would https://bun.sh/docs/api/websockets#create-a-websocket-server work?
=> style: fixed some grammar, rephrased sentences

docs/patterns/method-chaining.md
The name of the variable was missing in the code example so I added it.
=> fix: added a word in the example

docs/patterns/websocket.md
Fixed link to Bun.serve documentation for websockets.
The link was to old bun docs in the README.
=> fix: wrong link to documentation of Bun.serve using websockets

docs/patterns/websocket.md
- now says `const app = new Elysia()` instead of `new Elysia()` in the docs
=> docs: (minor) update code examples

docs/concept/derive.md, docs/concept/guard.md, docs/concept/handler.md, docs/concept/middleware.md, docs/concept/numeric.md
Fixed some small wording errors and reworked few sentences. This is to improve readability and provide more seamless introduction to the framework.
=> Fix wording in Concepts section

docs/patterns/dependency-injection.md
In the example, the state is set to 'redis' but once deconstruct happens, it changes to 'db'
=> docs: fix state example from db to redis

docs/plugins/eden/treaty.md
There is incorrect syntax used in `docs/plugins/eden/treaty.md`
=> Fix syntax

docs/concept/config.md
I was navigating `concept/config` on the docs and the URL for the WebSocket module points to the old URL [@elysiajs/websocket](https://github.com/elysiajs/elysia-websocket)
This PR just changes the link to point to the documentation itself
=> fix: WebSocket URL

components/midori/type-strict.vue
This PR cleans up the code in the type-strict.vue file by removing extra curly braces and parentheses.
Current code:
```js
new Elysia()
.post(
'/profile',
({ body }) => body,
{
body: t.Object({
username: t.String()
})
})
})
.listen(3000)
```
Update:
```js
new Elysia()
.post(
'/profile',
({ body }) => body,
{
body: t.Object({
username: t.String()
})
}
)
.listen(3000)
```
=> fix: update type-strict code example

docs/concept/handler.md
Need a closing parentheses to close the JSON.stringify 
```
app.get('/', () => new Response(
JSON.stringify({
'vtuber': [
'Shirakami Fubuki',
'Inugami Korone'
]
}, {
headers: {
'Content-Type': 'application/json'
}
})
)
```
=> Update handler.md - Need to add a closing parentheses 

docs/plugins/cors.md
The correct key is allowedHeaders not allowHeaders.
=> Fix cors configuration key in documentation

docs/patterns/file-upload.md, docs/patterns/lazy-loading-module.md
While trying to use File upload, I came across these invalid imports, which don't work with the prod version. This PR changes those from `../src` → `elysiajs`
Thanks!
=> 🔧 fix: invaild imports

docs/quick-start.md
[As of Bun v1.0.0](https://bun.sh/blog/bun-v1.0#changelog-since-v0-8), `bun dev` runs the "dev" script from package.json. Therefore the "run" command is not necessary.
This PR changes the Quick Start page to show `bun dev` instead of `bun run dev`.
=> Change `bun run dev` to `bun dev`

docs/blog/elysia-05.md, docs/concept/explicit-body.md, docs/concept/life-cycle.md, docs/concept/numeric.md, docs/concept/plugin.md, docs/concept/route.md, docs/concept/state-decorate.md, docs/patterns/after-handle.md, docs/patterns/body-parser.md, docs/patterns/error-handling.md, docs/patterns/trace.md
Some documentation pages have incorrectly spelled words or grammatical problems, so this a general pass-over to fix some of those issues.
- Restructured some sentences for better clarity
- Added some plurals where necessary.
- Added articles (a/an/the) to improve readability.
=> Fix Documentation Typos/Grammar

docs/concept/handler.md
The missing closing parenthesis here makes at seem as though the Response Options should be the second argument provided to the JSON.stringify method instead of the Response constructor. Adding the closing parenthesis clarifies this point.
=> Missing closing paren in example Response construction

docs/introduction.md
Verbs in the infinitive (like "to fit") should not be conjugated for number, person, or tense. In the corrected text "to fits" is incorrectly conjugated to reflect the third person. This change corrects that.
=> Fixed Typo

docs/plugins/cors.md
When reading the documentation I noticed some errors, which I'm assuming are from copy and pasting the `methods` entry 🙂. 
I changed the `methods` wording to `headers`.
I also fixed a typo, as the `exposedHeaders` field should be setting the `Access-Control-Expose-Headers` header instead of `Access-Control-Exposed-Headers`, as per the Mozilla docs. Because of this, however, I also noticed a bug in `@elysia/cors`, as it is indeed setting it as "Exposed" instead of what it should be; "Expose". Just wanted to share that, but I cannot fix that in this repo, of course.
=> Typos in CORS documentation

docs/patterns/cookie.md
In the cookie schema documentation, it is using the cookie name `name`, but the schema refers to the cookie name `value`.
=> Fix cookie schema example

docs/plugins/graphql-yoga.md
The GraphQL Yoga plugin docs originally directed users to `/swagger` (same text as in the Swagger plugin docs), I revised this to have corrected details about GraphQL and GraphiQL.
=> Fix endpoint access details typo (Swagger -> GraphQL)

docs/essential/context.md
1. Unnecessary Elysia context key (path) removed
2. Changed Path name -> Pathname
3. Fixed TypeError "❌ TypeError: version doesn't exist in store" -> // ❌ TypeError: counter doesn't exist in store
=> fix, update: essential -> context.md

docs/quick-start.md
Changed a typo that referenced an unrelated project (Next.js)
=> Update quick-start.md typo

docs/blog/elysia-05.md, docs/essential/route.md, docs/life-cycle/trace.md
This PR is for #208.
There have some links that navigate to undefined page or page not found.
So, I have updated these links to navigate to an existing page.
updated links:
`/concept/explicit-body` => `/life-cycle/parse.html#explicit-body`
`/concept/numeric` => `/validation/elysia-type.html#numeric`
`/essential/lifecycle-event` => `/essential/life-cycle`
`/concept/error-handling` => `/life-cycle/on-error`
`/concept/life-cycle` => `/essential/life-cycle`
---
If you have any feedback or suggestions, please let me know.
=> fix: update page not found links

docs/at-glance.md
IMO would be marginally easier to follow along if the port stays the same within the same at a glance page. 
Took me a few seconds to realize when following step by step that when I made the changes on my editor and I wasn't seeing what I expected was because the port the server was running on was no longer the same as in the beginning of the at a glance page.
=> improve at glance port consistency

docs/at-glance.md
In the same topic seem to use 'compile-time' word, this PR will make the another one be the same for more consistency
=> docs: add dash to compile-time in at-glance.md

docs/eden/installation.md
Error at the Eden Installation's example:
More detail at [stackoverflow - In case of dot notation to access a value, the property key must be a valid identifier](https://stackoverflow.com/questions/29888256/using-integer-keys-with-dot-notation-to-access-property-in-javascript-objects).
=> fix: example when property key is invalid

docs/eden/overview.md
There is a small typo in the Eden overview which refers to "`RRC`-like" instead of "`RPC`-like" as in other occasions.
=> Fix RPC typo

docs/integrations/custom-404.md
The code example was missing curly brackets
=> Fix incorrect code example on `Integrations / Custom 404` page

docs/plugins/cors.md
The original example would also match for example "*xsaltyaomycom" which is probably what is intended.
=> Update top domain regexp example.

docs/patterns/remapping.md
Fix typo "The => To" and merge sentences for improved clarity and flow in Affix function description.
=> Updates to Affix section in remapping.md

docs/api/constructor.md, docs/at-glance.md, docs/concept/schema.md, docs/concept/state-decorate.md, docs/eden/fetch.md, docs/eden/installation.md, docs/eden/overview.md, docs/eden/test.md, docs/eden/treaty.md, docs/essential/context.md, docs/essential/handler.md, docs/essential/path.md, docs/essential/plugin.md, docs/essential/route.md, docs/essential/schema.md, docs/essential/scope.md, docs/index.md, docs/integrations/astro.md, docs/integrations/nextjs.md, docs/integrations/sveltekit.md, docs/introduction.md, docs/life-cycle/after-handle.md, docs/life-cycle/before-handle.md, docs/life-cycle/on-error.md, docs/life-cycle/on-response.md, docs/life-cycle/overview.md, docs/life-cycle/trace.md, docs/patterns/group.md, docs/patterns/websocket.md
I haven't gone through every file in the repo, but these are fixes for a few obvious spelling/grammar mistakes I caught.
=> Some spelling and grammar fixes

docs/blog/elysia-08.md
From [Discord](https://discord.com/channels/1044804142461362206/1188216452919078972/1188216452919078972)
=> 🔧 fix: typo in elysia's 0.8 blog post

docs/life-cycle/map-response.md
- missing `Content-Encoding` & `Content-Type`
- type-error with `Bun.gzipSync` → `Uint8Array`
=> 🔧 fix: map response example

docs/life-cycle/map-response.md
It seemed like this sentence should say `mapResponse` instead of `afterHandle`, but let me know if I'm wrong about this.
=> Fix sentence in mapResponse docs

docs/validation/primitive-type.md
1. Extra `;` char
2. Code snippet doesn't have language like the one above
=> Fix couple of typos in primitive-type.md

docs/life-cycle/on-error.md
Very minor spelling fix in docs of `Eylsia.error` to `Elysia.error`.
=> fix: Eylsia.error to Elysia.error

docs/validation/schema-type.md
This pull request includes updates to our documentation on query parameters. The changes are twofold:
1. **Clarification on Query Parameters and Strings**: Improved the distinction between query strings and parameters to enhance readability and precision.
2. **String Type Requirement for Query Parameters**: Added a note specifying that all query parameters must be strings due to URL encoding constraints. This clarification addresses potential confusion, as both the Eden Treaty and validation libraries suggest broader type support. However, the technical requirement for string types is evident upon reviewing the implementation in [fetch/index.ts](https://github.com/elysiajs/eden/blob/main/src/fetch/index.ts) and [treaty/utils.ts](https://github.com/elysiajs/eden/blob/main/src/treaty/utils.t …
=> docs: update docs on types of query params

docs/index.md
This fixes these backticks that render at the bottom of https://elysiajs.com/:
=> fix: removed redundant backticks from the end of the `index.md` page

docs/essential/route.md
I changed the code snippet of demo1 to use the same words with the interactive window of demo1 for consistency.
=> Fixed: change words in docs/essential/route.md

docs/essential/scope.md
I tried to check this response example on local but it works well.
then I deployed on website `onBeforeHandle ` didn't works  and I don't know why.
I decide to mock response example and pass to props instead.
GET `/inner ` response got
but actually response should be
`/child` & `/parent` should be overwrite w/ `'hi'`
=> fix: essential/scope response example

docs/life-cycle/overview.md
- docs/life-cycle/overview.md
- Map Response Card
- link change from 'on-error' to 'map-response '.
=> docs: Correct overview Map Response Card link

docs/plugins/overview.md
This plugin is used to compress all responses that will be sent to the client, especially responses in the form of text (json/string).
Supports brotli, gzip, and deflate compression and can be set which compression algorithm will be used, such as ordering it to only support gzip and deflate compression.
Automatically detects which encodings are supported by the client using the `accept-encoding` header.
=> Submit Compression Plugin

docs/.vitepress/config.ts
Fixed an issue where the "Bearer" had multiple entries in the plugins section of the sidebar.
=> fix: bearer had multiple entries in plugins

docs/at-glance.md
Just notice these and wanted to fix them :)
Thanks for the great work so far!
=> docs: fix some typos on the "At glance" page

docs/validation/schema-type.md
The example for the query schema type is printed as an object, shouldn't it be shown as a url like the very fist example of the page ?
Like the URL column of this picture: 
Also added a valid example of using mandatory name along with optional alias.
=> Update query example schema-type.md

docs/plugins/overview.md
I've been asked to add prismabox to the plugin list in the elysia docs: https://github.com/m1212e/prismabox/discussions/17
Since it's not a "real" plugin in the elysia way, I opened a new list for projects that go well with elysia but are not plugins as per elysias definition.
=> Add prismabox to the docs

.gitignore, docs/eden/treaty/response.md
docs: include reference to the `error()` utility
* add reference to include the `error()` utility from Elysia
* update examples to import `error`
* add minor grammar fixes
=> docs: include reference to the `error()` utility

docs/eden/treaty/websocket.md
I've just been reading through the documentation. I found that Treaty's WebSocket example produces an error that the connection is not in the right state. My friend @dreamqip found that the problem was that `send` was running before the connection had been. That's what I'm suggesting to change. Hope it helps!
=> fix(treaty): send a message once the connection is opened

docs/essential/plugin.md
Modify the Playground component to use 'demo2' instead of 'demo3' in the 'plugin.md' file, particularly in the 'Functional Callback' section, to ensure the fetch API playground retrieves the correct path.
=> Update Playground component to use demo2 instead of demo3 in plugin.md

docs/plugins/html.md
Hey,
when I tried to use the Html plugin with JSX in a Typescript project, I always got the following error: `Cannot find name 'Html'. Did you mean 'html'?`. After some trial and error, I got it to work by adding the following import:
```ts
import { Html } from "@elysiajs/html";
```
It is important to that it starts with an uppercase letter. As also seen here, where someone else had the same problem: https://github.com/elysiajs/elysia-html/issues/96
Therefore I would like to add the import to the documentation with this PR ^^
=> Add uppercase html import for html plugin

docs/plugins/overview.md
The link to the BunSai repo no longer works. I have only found one repo with the name. The commits in the repo would also match the old URL. Unfortunately, I can't say for sure whether this is really the ‘right’ repo. Alternatively, maybe we could remove the link.
=> Fix broken BunSai link

docs/plugins/swagger.md
It wasn't clear how to get the OpenAPI spec. Had to dig through the plugin code.
=> Show where to get the raw OAPI spec

docs/quick-start.md
I think it's worth adding some parameters because for now this command is show the result inthe console.
add `--outdir` to specify directory where bundled file will be created and also `--target bun` because it is the best practice to run in Bun (but I know that Elysia WinterCG is compatible and the user may want to build a serverless environment)
> For generating bundles that are intended to be run by the Bun runtime. In many cases, it isn't necessary to bundle server-side code; you can directly execute the source code without modification. However, bundling your server code can reduce startup times and improve running performance.
> 
> All bundles generated with target: "bun" are marked with a special // @bun pragma, which indicates to the Bun runtime that there's no need to …
=> 📘: add some parameters to `build` script at `quick-start` page 

docs/integrations/drizzle.md
Changes:
- Reason for rename: better to match styling with "https://orm.drizzle.team/docs/typebox" guide.
- Return the body as response directly because `createUser` is previous example was not a callable.
PS:
- $defaultFn is drizzle is a runtime function hence will only be triggered when `user` is inserted via drizzle-orm client. So returned body will not have `id` field.
=> fix: drizzle integration example

docs/patterns/deployment.md
Spelling error in the heading for Railway Deployments
=> 📘Doc: Spelling Error in Documentation for Production Deployment page

docs/integrations/cheat-sheet.md
Location: Cheat Sheet page under the OpenAPI Documentation
Link leads to patterns/documentation instead of patterns/openapi
=> 📘Docs:  [Bug] Link leads to 404 Page

docs/integrations/cheat-sheet.md
This PR adjusts the `418` error message to match the correct message and other examples in the Elysia code.
=> fix: typo in 418 error message

docs/patterns/mount.md
I fixed a typo.
```ts
import Hono from 'hono'
```
is not workable.
I changed to
```ts
import { Hono } from 'hono'
```
=> 📘doc: fix example of importing Hono

docs/essential/handler.md
=> 📘doc: fix typo

docs/integrations/cheat-sheet.md
=> fix the broken link in the group section.

docs/essential/handler.md
Eden link in https://elysiajs.com/essential/handler.html#set-error  refers to overview/eden 
leading to https://elysiajs.com/overview/eden.html which is 404.
overview/eden -> eden/overview
=> 📘doc: fix broken link

docs/plugins/overview.md
Spelling mistake fix on the plugins overview page.
=> 📘 chore: typo

components/fern/benchmark.vue, components/fern/beyond.vue, components/fern/easy.vue, components/fern/features.vue, components/fern/sponsor.vue, components/fern/test.vue, docs/at-glance.md
This PR fixes a handful of grammatical issues on the Elysia homepage and "at-glance" page. Note that we probably also need to update `.vitepress/config.ts` to rename the latter page in the sidebar to "At a glance" in addition to updating its url as a follow-up (with a redirect for the old url to prevent bookmarked links from breaking). But given that this is my first PR for this project, I wanted to start just the smaller copy changes before trying anything more substantial.
I was not able to get automatic code formatting to work locally, so likely some whitespace changes will need to be reformatted.
=> 📘 doc: fix grammar on homepage and at-a-glance

docs/patterns/mount.md
I have no experience with either Elysia or Hono. However, I briefly set up the case locally, and it seems that, as documented, it leads to a syntax error.
=> Fix typo in mount.md

docs/eden/installation.md, docs/essential/best-practice.md, docs/essential/handler.md, docs/essential/life-cycle.md, docs/essential/plugin.md, docs/essential/route.md, docs/essential/validation.md, docs/key-concept.md, docs/tutorial.md
This PR is a set of small fixes on all pages from the sections `Getting Started` and `Essential`.
I'll work later on the rest of the pages.
I'm opening a single PR for all of them because I think it'll be easier to review (just check the individual commits) - if someone prefers, I can split it into smaller PRs.
- [chore: avoid warning for tree language not loaded](https://github.com/elysiajs/documentation/commit/ddbf547dbef5b60eefb9ac19281a696eaad34580)
Currently, there is no syntax highlight for `tree` ([see on prod](https://elysiajs.com/eden/installation)), so I just removed `tree` to suppress this warning.
(https://github.com/elysiajs/documentation/commit/ddbf547dbef5b60eefb9ac19281a696eaad34580)
- [fix break links on the pages from Getting Started and …
=> General fixes on the pages from `Getting Started` and `Essential`

docs/eden/installation.md, docs/eden/treaty/config.md, docs/eden/treaty/legacy.md, docs/integrations/cheat-sheet.md, docs/patterns/configuration.md, docs/patterns/cookie.md, docs/patterns/trace.md, docs/patterns/unit-test.md, docs/patterns/websocket.md, docs/plugins/cors.md, docs/plugins/graphql-apollo.md, docs/recipe/drizzle.md, docs/recipe/openapi.md, docs/recipe/opentelemetry.md
This PR is a continuation for https://github.com/elysiajs/documentation/pull/459
- [fix typos and formatting on pages from Patterns to Integration](https://github.com/elysiajs/documentation/commit/ee84674b1fefd4525d8a423c90e378a06ae7a6f7)
- [fix break links from `Patterns` to `Integration` (and `Cheat Seet`)](https://github.com/elysiajs/documentation/commit/7eed06bd0033a2800469f8cf8be41e6cda3052e9)
- [remove an unnecessary section divider](https://github.com/elysiajs/documentation/commit/f09f6aeaa87897551e063916eb946b5c3a94fc74)
=> General fixes on the pages from `Patterns` to `Integration`

docs/quick-start.md
When you select the tab for installing Elysia for Node in the quick start guide, the first instruction to install Node accidentally has the following text:
> You can install Bun with the command below:
This replaces the reference to "Bun" with "Node.js", to be consistent with the code snippet below installing Node.js with Brew.
```diff
- You can install Bun with the command below:
+ You can install Node.js with the command below:
```
In addition, the next section has two different tabs, one for TS and one for JS. If you select the JS one, it warns you:
> Using Elysia with TypeScript will miss out on some features auto-completion, advanced type checking and end-to-end type safety which is the core feature of Elysia.
_(before)_
I think the "with" was meant to be "without", but then I …
=> Fixing Quick Start Node install instructions & Warning if not using TypeScript

docs/tutorial.md
Previously, it would not highlight the code that was removed.
before: 
after:
=> fix: fix diff

docs/essential/life-cycle.md, docs/essential/route.md
Found a few areas of improvement while reading the docs:
1. The `/essential/route.html#optional-path-parameters` demo needed to be swapped with the `/essential/route.html#custom-method` as they were mismatched
2. The comment on the `/essential/life-cycle.html#to-throw-or-to-return` code snippet incorrectly stated that the throw example would not be caught by the `onError` handler
3. Also changed the default route on the `/essential/life-cycle.html#to-throw-or-to-return` to show the throw handler first to match the order in which the docs presents the error handling scenarios
Thanks!
=> Fix route documentation demo order & lifecycle throw demo comment

docs/quick-start.md
Issue Encountered:
While attempting to create a `tsconfig.json` file with `npx tsc init`, I encountered the following error:
`Could not resolve the path 'init'...`
Solution:
After a quick search, I discovered that changing `init` to `--init` resolved the issue successfully, allowing me to create the `tsconfig.json` file without further problems.
If there is any misunderstanding on my side, please disregard the edit.
=> fix: `npx tsc init` to `npx tsc --init`

docs/essential/handler.md
The `pattern` option of `t.String` must be the string contents of a RegEx, excluding the `/` delimiters. I tripped up on this when trying to follow this example and hoping to spare others the same footgun.
=> fix: Typo for pattern regex param

docs/plugins/overview.md
New Sentry plugin
* [GitHub](https://github.com/johnny-woodtke/elysiajs-sentry/)
* [npm package](https://www.npmjs.com/package/elysiajs-sentry)
I was recommended to add a Sentry instrumentation guide to the docs in [this discussion](https://github.com/elysiajs/elysia/discussions/994). I felt the best way to do this was to turn it into a plugin and add it to the community plugins list.
In this PR, I also fixed a typo, fixed some capitalization, and sorted the plugin list (moved logging plugins up on the list to be grouped with other logging plugins).
=> Community plugins: add Sentry plugin; format, sort list

docs/tutorial.md
The `sign-up` and `sign-in` has been written backwards.
=> docs(tutorial): fix sign-in and sign-up typos

docs/eden/overview.md
This pull request addresses a typo in the API call for the '/nendoroid/:id' endpoint in the overview example. 
The method was incorrectly labeled as `POST`, while it should be `PUT`.
=> fix typo: change method from POST to PUT in overview API call

docs/quick-start.md
The current link takes you to a Roblox community 💀
=> fix: Discord link

components/blog/Landing.vue, components/blog/Layout.vue, components/nearl/card.vue, components/nearl/playground.vue, docs/essential/validation.md, tsconfig.json
This PR fixes a couple of warnings when running the website.
I'm not fluent in Vue, but it seems to be running well.
- The [first commit](https://github.com/elysiajs/documentation/pull/462/commits/efc7cc4827fc560295820bbd1558aba2fd0ffd89) fixes this warning when building:
> [@vue/compiler-sfc] `defineProps` is a compiler macro and no longer needs to be imported"
The fix is just removing all the `defineProps` imports.
- The [second commit](https://github.com/elysiajs/documentation/pull/462/commits/26feb6d4d09e611159af644fbc3de3b2652c21cf) fixes this warning when rendering the `/essential/validation.html` page:
> `<tr>` cannot be child of `<table>`
The fix is wrapping the `<table>` children with `<tbody>`. It seems that we already do it when building for production, but we need to …
=> Fix some development warnings

docs/essential/structure.md
Hi, good morning! This PR replaces [this broken link](https://elysiajs.com/validation/reference-model.html#reference-model) with [this working one](https://elysiajs.com/essential/validation.html#reference-model)
This link was similarly replaced elsewhere in the documentation in commit 2d484734355ec468559b3a8b43fb58c0670fa37f
Fixes #424
=> docs: Replace broken link to reference-model

docs/quick-start.md
In `yarn` and `pnpm`, adding `devDependencies` require using `-D` instead of `-d`.  
Using lowercase `-d` will cause `yarn` unable to handle with `Unknown Syntax Error` (supporting log provided below):  
```
PS C:\Users\alex4386\git\***> yarn add -d tsx @types/node typescript
Unknown Syntax Error: Unsupported option name ("-d").
$ yarn add [--json] [-F,--fixed] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
```  
This PR fixes the documentation's command snippet by using `-D` instead of `-d`.
=> Fix script for adding `devDependencies` on `pnpm` and `yarn`

docs/recipe/drizzle.md
according to the official docs.
- https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides
- https://bun.sh/docs/install/overrides
=> docs(drizzle): fix typo  key for package.json

docs/plugins/overview.md
This plugin provides standard OAuth2 resource server functionality. Compared to `@elysiajs/jwt`, this package focuses solely on validating tokens from external OAuth2 providers against JWKS endpoints.
This enables secure integration with identity providers like Auth0, Okta, Ory, and custom OAuth2 servers. It is meant to be used in implementing protected APIs in microservice architectures where authentication is handled by a separate authorization server, i.e. an auth gateway.
=> Add a community plugin for an OAuth2 resource server

docs/integrations/nuxt.md
fix syntax error in api.ts example of Integration with Nuxt
=> 📝doc: Fix syntax error in api.ts example Integration with Nuxt

docs/key-concept.md
Closes https://github.com/elysiajs/documentation/issues/543
=> 📘 doc: fix inconsistent between doc and code 

docs/plugins/trpc.md
The code block in the docs appear to cover too much information, also including the markdown heading. This PR aims to fix this by fixing the range of the code block in the documentation.
=> docs: fix unintended code block level in TRPC page

docs/essential/best-practice.md
I know it's a silly thing but there's no `should` export in bun:test, the correct import should be `expect`.
=> docs: Replace should with expect in best-practice.md

docs/essential/best-practice.md
Just a quick fix to the `AuthModel` import path in `best-practice.md`. It was pointing to `./service`, but it should be` ./model`.
=> docs(fix): AuthModel import

docs/integrations/sveltekit.md
Adds `fallback`, which functions as a catch-all for methods, into the SvelteKit integration docs. This can help prevent errors due to some methods not being handled with Elysia.
=> Use fallback for SvelteKit methods

docs/integrations/cloudflare-worker.md
I just tried out the Cloudflare Workers adapter, and it seems the import file name should be `cloudflare-worker`, not `cloudflare`. :sweat:
ref: https://github.com/elysiajs/elysia/blob/eb4d126d5d0845cdcf4d3cb52dd949f2507eaf92/package.json#L131
=> Fix import in sample code of `integrations/cloudflare-worker`
